// Generated from src/data/places.json by `npm run sync:places`. Do not edit by hand.
// Keyword table used to put a headline somewhere on the map.
self.MAP_NEWS_PLACES = [
  {"id":"beijing","keys":["beijing","china","chinese","pboc"],"region":"Beijing","city":"Beijing","country":"China","lat":39.9042,"lng":116.4074},
  {"id":"hong-kong","keys":["hong kong","hang seng"],"region":"Hong Kong","city":"Hong Kong","country":"China","lat":22.3193,"lng":114.1694},
  {"id":"seoul","keys":["seoul","south korea","bank of korea","kospi"],"region":"Seoul","city":"Seoul","country":"South Korea","lat":37.5665,"lng":126.978},
  {"id":"tokyo","keys":["tokyo","japan","japanese","boj","nikkei","yen"],"region":"Tokyo","city":"Tokyo","country":"Japan","lat":35.6762,"lng":139.6503},
  {"id":"taipei","keys":["taipei","taiwan","tsmc"],"region":"Taipei","city":"Taipei","country":"Taiwan","lat":25.033,"lng":121.5654},
  {"id":"singapore","keys":["singapore","mas "],"region":"Singapore","city":"Singapore","country":"Singapore","lat":1.3521,"lng":103.8198},
  {"id":"mumbai","keys":["mumbai","rbi","sensex","nifty"],"region":"Mumbai","city":"Mumbai","country":"India","lat":19.076,"lng":72.8777},
  {"id":"new-delhi","keys":["new delhi","delhi","india","indian"],"region":"New Delhi","city":"New Delhi","country":"India","lat":28.6139,"lng":77.209},
  {"id":"jakarta","keys":["jakarta","indonesia"],"region":"Jakarta","city":"Jakarta","country":"Indonesia","lat":-6.2088,"lng":106.8456},
  {"id":"manila","keys":["manila","philippines"],"region":"Manila","city":"Manila","country":"Philippines","lat":14.5995,"lng":120.9842},
  {"id":"bangkok","keys":["bangkok","thailand"],"region":"Bangkok","city":"Bangkok","country":"Thailand","lat":13.7563,"lng":100.5018},
  {"id":"hanoi","keys":["hanoi","vietnam"],"region":"Hanoi","city":"Hanoi","country":"Vietnam","lat":21.0278,"lng":105.8342},
  {"id":"sydney","keys":["sydney","australia","australian","rba"],"region":"Sydney","city":"Sydney","country":"Australia","lat":-33.8688,"lng":151.2093},
  {"id":"wellington","keys":["wellington","new zealand","rbnz"],"region":"Wellington","city":"Wellington","country":"New Zealand","lat":-41.2865,"lng":174.7762},
  {"id":"london","keys":["london","britain","british","england","boe","ftse","gilt","uk"],"region":"London","city":"London","country":"United Kingdom","lat":51.5074,"lng":-0.1278},
  {"id":"paris","keys":["paris","france","french","macron"],"region":"Paris","city":"Paris","country":"France","lat":48.8566,"lng":2.3522},
  {"id":"berlin","keys":["berlin","germany","german","bundesbank","thyssenkrupp"],"region":"Berlin","city":"Berlin","country":"Germany","lat":52.52,"lng":13.405},
  {"id":"frankfurt","keys":["frankfurt","ecb","eurozone","euro zone","lagarde"],"region":"Frankfurt","city":"Frankfurt","country":"Germany","lat":50.1109,"lng":8.6821},
  {"id":"rome","keys":["rome","italy","italian"],"region":"Rome","city":"Rome","country":"Italy","lat":41.9028,"lng":12.4964},
  {"id":"madrid","keys":["madrid","spain","spanish"],"region":"Madrid","city":"Madrid","country":"Spain","lat":40.4168,"lng":-3.7038},
  {"id":"brussels","keys":["brussels","european union","nato","eu"],"region":"Brussels","city":"Brussels","country":"Belgium","lat":50.8503,"lng":4.3517},
  {"id":"amsterdam","keys":["amsterdam","netherlands","dutch"],"region":"Amsterdam","city":"Amsterdam","country":"Netherlands","lat":52.3676,"lng":4.9041},
  {"id":"zurich","keys":["zurich","switzerland","swiss","snb"],"region":"Zurich","city":"Zurich","country":"Switzerland","lat":47.3769,"lng":8.5417},
  {"id":"oslo","keys":["oslo","norway","norwegian","norges"],"region":"Oslo","city":"Oslo","country":"Norway","lat":59.9139,"lng":10.7522},
  {"id":"stockholm","keys":["stockholm","sweden","swedish","riksbank"],"region":"Stockholm","city":"Stockholm","country":"Sweden","lat":59.3293,"lng":18.0686},
  {"id":"helsinki","keys":["helsinki","rovaniemi","finland","finnish"],"region":"Helsinki","city":"Helsinki","country":"Finland","lat":60.1699,"lng":24.9384},
  {"id":"copenhagen","keys":["copenhagen","denmark","danish","maersk"],"region":"Copenhagen","city":"Copenhagen","country":"Denmark","lat":55.6761,"lng":12.5683},
  {"id":"warsaw","keys":["warsaw","poland","polish"],"region":"Warsaw","city":"Warsaw","country":"Poland","lat":52.2297,"lng":21.0122},
  {"id":"kyiv","keys":["kyiv","kiev","ukraine","ukrainian"],"region":"Kyiv","city":"Kyiv","country":"Ukraine","lat":50.4501,"lng":30.5234},
  {"id":"moscow","keys":["moscow","russia","russian","kremlin","putin"],"region":"Moscow","city":"Moscow","country":"Russia","lat":55.7558,"lng":37.6173},
  {"id":"istanbul","keys":["istanbul","turkey","türkiye","turkiye"],"region":"Istanbul","city":"Istanbul","country":"Türkiye","lat":41.0082,"lng":28.9784},
  {"id":"athens","keys":["athens","greece","greek"],"region":"Athens","city":"Athens","country":"Greece","lat":37.9838,"lng":23.7275},
  {"id":"cairo","keys":["cairo","egypt","egyptian","suez"],"region":"Cairo","city":"Cairo","country":"Egypt","lat":30.0444,"lng":31.2357},
  {"id":"jerusalem","keys":["jerusalem","israel","israeli","gaza","tel aviv"],"region":"Jerusalem","city":"Jerusalem","country":"Israel","lat":31.7683,"lng":35.2137},
  {"id":"tehran","keys":["tehran","iran","iranian"],"region":"Tehran","city":"Tehran","country":"Iran","lat":35.6892,"lng":51.389},
  {"id":"riyadh","keys":["riyadh","saudi","aramco","opec"],"region":"Riyadh","city":"Riyadh","country":"Saudi Arabia","lat":24.7136,"lng":46.6753},
  {"id":"dubai","keys":["dubai","uae","emirates"],"region":"Dubai","city":"Dubai","country":"United Arab Emirates","lat":25.2048,"lng":55.2708},
  {"id":"sanaa","keys":["yemen","houthi","red sea"],"region":"Sana'a","city":"Sana'a","country":"Yemen","lat":15.3694,"lng":44.191},
  {"id":"nairobi","keys":["nairobi","kenya"],"region":"Nairobi","city":"Nairobi","country":"Kenya","lat":-1.2921,"lng":36.8219},
  {"id":"lagos","keys":["lagos","nigeria"],"region":"Lagos","city":"Lagos","country":"Nigeria","lat":6.5244,"lng":3.3792},
  {"id":"johannesburg","keys":["johannesburg","south africa"],"region":"Johannesburg","city":"Johannesburg","country":"South Africa","lat":-26.2041,"lng":28.0473},
  {"id":"cape-town","keys":["cape town"],"region":"Cape Town","city":"Cape Town","country":"South Africa","lat":-33.9249,"lng":18.4241},
  {"id":"washington","keys":["washington","white house","federal reserve","fomc","powell","united states","trump"],"region":"Washington","city":"Washington","country":"United States","lat":38.9072,"lng":-77.0369},
  {"id":"new-york","keys":["new york","wall street","nasdaq","dow jones","s&p 500"],"region":"New York","city":"New York","country":"United States","lat":40.7128,"lng":-74.006},
  {"id":"los-angeles","keys":["los angeles"],"region":"Los Angeles","city":"Los Angeles","country":"United States","lat":34.0522,"lng":-118.2437},
  {"id":"mexico-city","keys":["mexico city","mexico","mexican"],"region":"Mexico City","city":"Mexico City","country":"Mexico","lat":19.4326,"lng":-99.1332},
  {"id":"ottawa","keys":["ottawa","canada","canadian"],"region":"Ottawa","city":"Ottawa","country":"Canada","lat":45.4215,"lng":-75.6972},
  {"id":"toronto","keys":["toronto"],"region":"Toronto","city":"Toronto","country":"Canada","lat":43.6532,"lng":-79.3832},
  {"id":"sao-paulo","keys":["são paulo","sao paulo","brazil","brazilian"],"region":"São Paulo","city":"São Paulo","country":"Brazil","lat":-23.5505,"lng":-46.6333},
  {"id":"buenos-aires","keys":["buenos aires","argentina"],"region":"Buenos Aires","city":"Buenos Aires","country":"Argentina","lat":-34.6037,"lng":-58.3816},
  {"id":"santiago","keys":["santiago","chile"],"region":"Santiago","city":"Santiago","country":"Chile","lat":-33.4489,"lng":-70.6693},
  {"id":"tbilisi","keys":["tbilisi","georgia"],"region":"Tbilisi","city":"Tbilisi","country":"Georgia","lat":41.7151,"lng":44.8271},
  {"id":"alabama","keys":["alabama","montgomery"],"region":"Alabama","city":"Montgomery","country":"United States","lat":32.3792,"lng":-86.3077},
  {"id":"alaska","keys":["alaska","anchorage"],"region":"Alaska","city":"Anchorage","country":"United States","lat":61.2181,"lng":-149.9003},
  {"id":"arizona","keys":["arizona","phoenix"],"region":"Arizona","city":"Phoenix","country":"United States","lat":33.4484,"lng":-112.074},
  {"id":"arkansas","keys":["arkansas","little rock"],"region":"Arkansas","city":"Little Rock","country":"United States","lat":34.7465,"lng":-92.2896},
  {"id":"colorado","keys":["colorado","denver"],"region":"Colorado","city":"Denver","country":"United States","lat":39.7392,"lng":-104.9903},
  {"id":"connecticut","keys":["connecticut","hartford"],"region":"Connecticut","city":"Hartford","country":"United States","lat":41.7658,"lng":-72.6734},
  {"id":"delaware","keys":["delaware","wilmington"],"region":"Delaware","city":"Wilmington","country":"United States","lat":39.7391,"lng":-75.5398},
  {"id":"florida","keys":["florida","miami","orlando","tampa"],"region":"Florida","city":"Miami","country":"United States","lat":25.7617,"lng":-80.1918},
  {"id":"georgia-us","keys":["atlanta"],"region":"Atlanta","city":"Atlanta","country":"United States","lat":33.749,"lng":-84.388},
  {"id":"hawaii","keys":["hawaii","honolulu"],"region":"Hawaii","city":"Honolulu","country":"United States","lat":21.3069,"lng":-157.8583},
  {"id":"idaho","keys":["idaho","boise"],"region":"Idaho","city":"Boise","country":"United States","lat":43.615,"lng":-116.2023},
  {"id":"illinois","keys":["illinois","chicago"],"region":"Illinois","city":"Chicago","country":"United States","lat":41.8781,"lng":-87.6298},
  {"id":"indiana","keys":["indiana","indianapolis"],"region":"Indiana","city":"Indianapolis","country":"United States","lat":39.7684,"lng":-86.1581},
  {"id":"iowa","keys":["iowa","des moines"],"region":"Iowa","city":"Des Moines","country":"United States","lat":41.5868,"lng":-93.625},
  {"id":"kansas","keys":["kansas","wichita"],"region":"Kansas","city":"Wichita","country":"United States","lat":37.6872,"lng":-97.3301},
  {"id":"kentucky","keys":["kentucky","louisville"],"region":"Kentucky","city":"Louisville","country":"United States","lat":38.2527,"lng":-85.7585},
  {"id":"louisiana","keys":["louisiana","new orleans"],"region":"Louisiana","city":"New Orleans","country":"United States","lat":29.9511,"lng":-90.0715},
  {"id":"maine","keys":["maine","portland, maine"],"region":"Maine","city":"Portland","country":"United States","lat":43.6591,"lng":-70.2568},
  {"id":"maryland","keys":["maryland","baltimore"],"region":"Maryland","city":"Baltimore","country":"United States","lat":39.2904,"lng":-76.6122},
  {"id":"massachusetts","keys":["massachusetts","boston"],"region":"Massachusetts","city":"Boston","country":"United States","lat":42.3601,"lng":-71.0589},
  {"id":"michigan","keys":["michigan","detroit"],"region":"Michigan","city":"Detroit","country":"United States","lat":42.3314,"lng":-83.0458},
  {"id":"minnesota","keys":["minnesota","minneapolis"],"region":"Minnesota","city":"Minneapolis","country":"United States","lat":44.9778,"lng":-93.265},
  {"id":"mississippi","keys":["mississippi","jackson"],"region":"Mississippi","city":"Jackson","country":"United States","lat":32.2988,"lng":-90.1848},
  {"id":"missouri","keys":["missouri","st. louis","kansas city"],"region":"Missouri","city":"St. Louis","country":"United States","lat":38.627,"lng":-90.1994},
  {"id":"montana","keys":["montana","billings"],"region":"Montana","city":"Billings","country":"United States","lat":45.7833,"lng":-108.5007},
  {"id":"nebraska","keys":["nebraska","omaha"],"region":"Nebraska","city":"Omaha","country":"United States","lat":41.2565,"lng":-95.9345},
  {"id":"nevada","keys":["nevada","las vegas","reno"],"region":"Nevada","city":"Las Vegas","country":"United States","lat":36.1699,"lng":-115.1398},
  {"id":"new-hampshire","keys":["new hampshire"],"region":"New Hampshire","city":"Concord","country":"United States","lat":43.2081,"lng":-71.5376},
  {"id":"new-jersey","keys":["new jersey"],"region":"New Jersey","city":"Newark","country":"United States","lat":40.7357,"lng":-74.1724},
  {"id":"new-mexico","keys":["new mexico","albuquerque"],"region":"New Mexico","city":"Albuquerque","country":"United States","lat":35.0844,"lng":-106.6504},
  {"id":"north-carolina","keys":["north carolina","charlotte","raleigh"],"region":"North Carolina","city":"Charlotte","country":"United States","lat":35.2271,"lng":-80.8431},
  {"id":"north-dakota","keys":["north dakota","fargo"],"region":"North Dakota","city":"Fargo","country":"United States","lat":46.8772,"lng":-96.7898},
  {"id":"ohio","keys":["ohio","cleveland","columbus","cincinnati"],"region":"Ohio","city":"Columbus","country":"United States","lat":39.9612,"lng":-82.9988},
  {"id":"oklahoma","keys":["oklahoma","oklahoma city"],"region":"Oklahoma","city":"Oklahoma City","country":"United States","lat":35.4676,"lng":-97.5164},
  {"id":"oregon","keys":["oregon","portland"],"region":"Oregon","city":"Portland","country":"United States","lat":45.5152,"lng":-122.6784},
  {"id":"pennsylvania","keys":["pennsylvania","philadelphia","pittsburgh"],"region":"Pennsylvania","city":"Philadelphia","country":"United States","lat":39.9526,"lng":-75.1652},
  {"id":"rhode-island","keys":["rhode island","providence"],"region":"Rhode Island","city":"Providence","country":"United States","lat":41.824,"lng":-71.4128},
  {"id":"south-carolina","keys":["south carolina","charleston"],"region":"South Carolina","city":"Charleston","country":"United States","lat":32.7765,"lng":-79.9311},
  {"id":"south-dakota","keys":["south dakota","sioux falls"],"region":"South Dakota","city":"Sioux Falls","country":"United States","lat":43.5446,"lng":-96.7311},
  {"id":"tennessee","keys":["tennessee","nashville","memphis"],"region":"Tennessee","city":"Nashville","country":"United States","lat":36.1627,"lng":-86.7816},
  {"id":"texas","keys":["texas","houston","dallas","austin","san antonio"],"region":"Texas","city":"Houston","country":"United States","lat":29.7604,"lng":-95.3698},
  {"id":"utah","keys":["utah","salt lake city"],"region":"Utah","city":"Salt Lake City","country":"United States","lat":40.7608,"lng":-111.891},
  {"id":"vermont","keys":["vermont","burlington"],"region":"Vermont","city":"Burlington","country":"United States","lat":44.4759,"lng":-73.2121},
  {"id":"virginia","keys":["virginia","richmond"],"region":"Virginia","city":"Richmond","country":"United States","lat":37.5407,"lng":-77.436},
  {"id":"washington-state","keys":["seattle","washington state"],"region":"Seattle","city":"Seattle","country":"United States","lat":47.6062,"lng":-122.3321},
  {"id":"west-virginia","keys":["west virginia"],"region":"West Virginia","city":"Charleston","country":"United States","lat":38.3498,"lng":-81.6326},
  {"id":"wisconsin","keys":["wisconsin","milwaukee","madison"],"region":"Wisconsin","city":"Milwaukee","country":"United States","lat":43.0389,"lng":-87.9065},
  {"id":"wyoming","keys":["wyoming"],"region":"Wyoming","city":"Cheyenne","country":"United States","lat":41.14,"lng":-104.8202},
  {"id":"california","keys":["california","sacramento","silicon valley"],"region":"California","city":"Sacramento","country":"United States","lat":38.5816,"lng":-121.4944},
  {"id":"san-francisco","keys":["san francisco"],"region":"San Francisco","city":"San Francisco","country":"United States","lat":37.7749,"lng":-122.4194},
  {"id":"quebec","keys":["quebec","montreal"],"region":"Quebec","city":"Montreal","country":"Canada","lat":45.5017,"lng":-73.5673},
  {"id":"ontario","keys":["ontario"],"region":"Ontario","city":"Toronto","country":"Canada","lat":43.6532,"lng":-79.3832},
  {"id":"british-columbia","keys":["british columbia","vancouver"],"region":"British Columbia","city":"Vancouver","country":"Canada","lat":49.2827,"lng":-123.1207},
  {"id":"alberta","keys":["alberta","calgary","edmonton"],"region":"Alberta","city":"Calgary","country":"Canada","lat":51.0447,"lng":-114.0719},
  {"id":"manchester","keys":["manchester"],"region":"Manchester","city":"Manchester","country":"United Kingdom","lat":53.4808,"lng":-2.2426},
  {"id":"scotland","keys":["scotland","edinburgh","glasgow"],"region":"Scotland","city":"Edinburgh","country":"United Kingdom","lat":55.9533,"lng":-3.1883},
  {"id":"wales","keys":["wales","cardiff"],"region":"Wales","city":"Cardiff","country":"United Kingdom","lat":51.4816,"lng":-3.1791},
  {"id":"northern-ireland","keys":["northern ireland","belfast"],"region":"Northern Ireland","city":"Belfast","country":"United Kingdom","lat":54.5973,"lng":-5.9301},
  {"id":"munich","keys":["munich","bavaria"],"region":"Munich","city":"Munich","country":"Germany","lat":48.1351,"lng":11.582},
  {"id":"milan","keys":["milan"],"region":"Milan","city":"Milan","country":"Italy","lat":45.4642,"lng":9.19},
  {"id":"barcelona","keys":["barcelona"],"region":"Barcelona","city":"Barcelona","country":"Spain","lat":41.3874,"lng":2.1686},
  {"id":"vienna","keys":["vienna","austria"],"region":"Vienna","city":"Vienna","country":"Austria","lat":48.2082,"lng":16.3738},
  {"id":"prague","keys":["prague","czech"],"region":"Prague","city":"Prague","country":"Czechia","lat":50.0755,"lng":14.4378},
  {"id":"budapest","keys":["budapest","hungary"],"region":"Budapest","city":"Budapest","country":"Hungary","lat":47.4979,"lng":19.0402},
  {"id":"bucharest","keys":["bucharest","romania"],"region":"Bucharest","city":"Bucharest","country":"Romania","lat":44.4268,"lng":26.1025},
  {"id":"dublin","keys":["dublin","ireland","irish"],"region":"Dublin","city":"Dublin","country":"Ireland","lat":53.3498,"lng":-6.2603},
  {"id":"lisbon","keys":["lisbon","portugal"],"region":"Lisbon","city":"Lisbon","country":"Portugal","lat":38.7223,"lng":-9.1393},
  {"id":"osaka","keys":["osaka"],"region":"Osaka","city":"Osaka","country":"Japan","lat":34.6937,"lng":135.5023},
  {"id":"shanghai","keys":["shanghai"],"region":"Shanghai","city":"Shanghai","country":"China","lat":31.2304,"lng":121.4737},
  {"id":"shenzhen","keys":["shenzhen"],"region":"Shenzhen","city":"Shenzhen","country":"China","lat":22.5431,"lng":114.0579},
  {"id":"guangzhou","keys":["guangzhou"],"region":"Guangzhou","city":"Guangzhou","country":"China","lat":23.1291,"lng":113.2644},
  {"id":"kuala-lumpur","keys":["kuala lumpur","malaysia"],"region":"Kuala Lumpur","city":"Kuala Lumpur","country":"Malaysia","lat":3.139,"lng":101.6869},
  {"id":"islamabad","keys":["islamabad","pakistan","karachi"],"region":"Islamabad","city":"Islamabad","country":"Pakistan","lat":33.6844,"lng":73.0479},
  {"id":"dhaka","keys":["dhaka","bangladesh"],"region":"Dhaka","city":"Dhaka","country":"Bangladesh","lat":23.8103,"lng":90.4125},
  {"id":"colombo","keys":["colombo","sri lanka"],"region":"Colombo","city":"Colombo","country":"Sri Lanka","lat":6.9271,"lng":79.8612},
  {"id":"baghdad","keys":["baghdad","iraq"],"region":"Baghdad","city":"Baghdad","country":"Iraq","lat":33.3152,"lng":44.3661},
  {"id":"damascus","keys":["damascus","syria"],"region":"Damascus","city":"Damascus","country":"Syria","lat":33.5138,"lng":36.2765},
  {"id":"beirut","keys":["beirut","lebanon"],"region":"Beirut","city":"Beirut","country":"Lebanon","lat":33.8938,"lng":35.5018},
  {"id":"doha","keys":["doha","qatar"],"region":"Doha","city":"Doha","country":"Qatar","lat":25.2854,"lng":51.531},
  {"id":"kuwait-city","keys":["kuwait"],"region":"Kuwait","city":"Kuwait City","country":"Kuwait","lat":29.3759,"lng":47.9774},
  {"id":"muscat","keys":["muscat","oman"],"region":"Muscat","city":"Muscat","country":"Oman","lat":23.588,"lng":58.3829},
  {"id":"addis-ababa","keys":["addis ababa","ethiopia"],"region":"Addis Ababa","city":"Addis Ababa","country":"Ethiopia","lat":9.032,"lng":38.7469},
  {"id":"accra","keys":["accra","ghana"],"region":"Accra","city":"Accra","country":"Ghana","lat":5.6037,"lng":-0.187},
  {"id":"casablanca","keys":["casablanca","morocco"],"region":"Casablanca","city":"Casablanca","country":"Morocco","lat":33.5731,"lng":-7.5898},
  {"id":"tunis","keys":["tunis","tunisia"],"region":"Tunis","city":"Tunis","country":"Tunisia","lat":36.8065,"lng":10.1815},
  {"id":"algiers","keys":["algiers","algeria"],"region":"Algiers","city":"Algiers","country":"Algeria","lat":36.7538,"lng":3.0588},
  {"id":"lima","keys":["lima","peru"],"region":"Lima","city":"Lima","country":"Peru","lat":-12.0464,"lng":-77.0428},
  {"id":"bogota","keys":["bogota","bogotá","colombia"],"region":"Bogotá","city":"Bogotá","country":"Colombia","lat":4.711,"lng":-74.0721},
  {"id":"caracas","keys":["caracas","venezuela"],"region":"Caracas","city":"Caracas","country":"Venezuela","lat":10.4806,"lng":-66.9036},
  {"id":"canberra","keys":["canberra","melbourne"],"region":"Melbourne","city":"Melbourne","country":"Australia","lat":-37.8136,"lng":144.9631},
]
